### ISSUE TITLE
Java/1.8 wrapper doesn't pass sanitycheck on 6.x Lmod

### ISSUE THREAD

**Issue by zao** [easybuilders/easybuild#462]
The sanity check for Java/1.8 with older Lmod versions doesn't complete successfully.
It happens on both Debian 9.5's `6.6.0-2` Lmod and upstream `6.6.3` installed from tarball.
If I make a leap and install upstream `7.8.6` it's passes fine.
(I have locally adjusted the minimum required version in EB 3.7.0 to make it accept Debian's Lmod version.)

Do we need a higher minimum required Lmod version if this `modulerc` thing is supposed to be universally used in 2018b toolchains and onward? It's already part of R-3.5.1, so has quite an impact.

If it's a local configuration problem, I'd be happy with additional datapoints refuting this too :)
```
== 2018-09-29 14:53:09,823 build_log.py:158 ERROR EasyBuild crashed with an error (at easybuild/software/EasyBuild/3.7.0/lib/python2.7/site-packages/vsc_base-2.8.3-py2.7.egg/vsc/utils/exceptions.py:124 in __init__): Module command 'module load Java/1.8' failed with exit code 1; stderr: Lmod has detected the following error: The following module(s) are unknown:
"Java/1.8"

Please check the spelling or version number. Also try "module spider ..."



; stdout: os.environ["LMOD_DEFAULT_MODULEPATH"] = "/tmp/eb-dtAb_2/tmp3ljzLW/all:/home/zao/.local/easybuild/modules/all:/etc/lmod/modules:/usr/share/lmod/lmod/modulefiles";
os.environ["MODULEPATH"] = "/tmp/eb-dtAb_2/tmp3ljzLW/all:/home/zao/.local/easybuild/modules/all:/etc/lmod/modules:/usr/share/lmod/lmod/modulefiles";
false
 (at easybuild/software/EasyBuild/3.7.0/lib/python2.7/site-packages/easybuild_framework-3.7.0-py2.7.egg/easybuild/tools/modules.py:672 in run_module)
```

**Comment by boegel** [comment]
@zao The `easybuild-framework` tests pass on top of Lmod 6.5.1, 6.6.3 and 7.7.16, and in https://github.com/easybuilders/easybuild-framework/pull/2597 also on top of Lmod 7.8.5, so if you use any of those versions, it should be sufficient.

Support for software-specific `.modulerc` files has been there since Lmod 5.6, so in theory any Lmod version newer than that should work, but there may be bugs in some specific versions that prevent the wrapper from being picked up.

Nevertheless, it should work with the upstream Lmod 6.6.3 with pretty much the default configuration, since we verify that in the framework tests...

Do you mind sharing your Lmod configuration (output of `ml --config`)?

**Comment by zao** [comment]
```
Modules based on Lua: Version 6.6.3  2016-11-13 15:27 -07:00
    by Robert McLay mclay@tacc.utexas.edu

Description                         Value
-----------                         -----
Allow TCL modulefiles               yes
Auto swapping                       yes
Case Independent Sorting            no
Colorize Lmod                       yes
Disable Same Name AutoSwap          no
Using dotfiles                      yes
Allow duplicate paths               no
Require Exact Match/no defaults     no
Export the module command           YES
LD_LIBRARY_PATH at config time      <empty>
LD_PRELOAD at config time           <empty>
Lmod version                        6.6.3
Lua Version                         Lua 5.2
System lua_json                     yes
System lua-term                     yes
Active lua-term                     true
MODULERCFILE                        /usr/local/lmod/etc/rc
avail: Include modulepath dir       no
MODULEPATH_ROOT                     NONE/modulefiles
number of cache dirs                0
Version ordering                    modern
Pager                               /usr/bin/less
Pager Options                       -XqMREF
Path to HashSum                     /usr/bin/sha1sum
Path to Lua                         /usr/bin
Pin Versions in restore             no
Pkg Class name                      Pkg
Lmod prefix                         /usr/local
Prepend order                       normal
Redirect to stdout                  no
Supporting Full Settarg Use         no
Site Pkg location                   standard
Ignore Cache                        no
Cached loads                        no
User cache valid time(sec)          86400
Write cache after (sec)             2
Threshold (sec)                     1
Tmod prepend PATH Rule              no
uname -a                            Linux dagur 4.4.0-17134-Microsoft #285-Microsoft Thu Aug 30 17:31:00 PST 2018 x86_64 GNU/Linux
Admin file                          /usr/local/lmod/etc/admin.list
Does Admin file exist               no
Check TCL modules for magic string  no


Active RC file(s):
------------------
/usr/local/lmod/6.6.3/init/lmodrc.lua


    ----------------------------------------------------------------------------------------------------------

 Lmod Property Table:
    ----------------------------------------------------------------------------------------------------------



propT = {
  arch = {
    displayT = {
      gpu = {
        ["color"] = "red",
        ["doc"] = "built for GPU",
        ["long"] = "(g)",
        ["short"] = "(g)",
      },
      ["gpu:mic"]  = {
        ["color"] = "red",
        ["doc"] = "built natively for MIC and GPU",
        ["long"] = "(g,m)",
        ["short"] = "(gm)",
      },
      ["gpu:mic:offload"]  = {
        ["color"] = "red",
        ["doc"] = "built natively for MIC and GPU and offload to the MIC",
        ["long"] = "(g,m,o)",
        ["short"] = "(@)",
      },
      mic = {
        ["color"] = "blue",
        ["doc"] = "built for host and native MIC",
        ["long"] = "(m)",
        ["short"] = "(m)",
      },
      ["mic:offload"]  = {
        ["color"] = "blue",
        ["doc"] = "built for host, native MIC and offload to the MIC",
        ["long"] = "(m,o)",
        ["short"] = "(*)",
      },
      offload = {
        ["color"] = "blue",
        ["doc"] = "built for offload to the MIC only",
        ["long"] = "(o)",
        ["short"] = "(o)",
      },
    },
    validT = {
      ["gpu"] = 1,
      ["mic"] = 1,
      ["offload"] = 1,
    },
  },
  lmod = {
    displayT = {
      sticky = {
        ["color"] = "red",
        ["doc"] = "Module is Sticky, requires --force to unload or purge",
        ["long"] = "(S)",
        ["short"] = "(S)",
      },
    },
    validT = {
      ["sticky"] = 1,
    },
  },
  state = {
    displayT = {
      experimental = {
        ["color"] = "blue",
        ["doc"] = "Experimental",
        ["long"] = "(E)",
        ["short"] = "(E)",
      },
      obsolete = {
        ["color"] = "red",
        ["doc"] = "Obsolete",
        ["long"] = "(O)",
        ["short"] = "(O)",
      },
      testing = {
        ["color"] = "green",
        ["doc"] = "Testing",
        ["long"] = "(T)",
        ["short"] = "(T)",
      },
    },
    validT = {
      ["experimental"] = 1,
      ["obsolete"] = 1,
      ["testing"] = 1,
    },
  },
  status = {
    displayT = {
      active = {
        ["color"] = "yellow",
        ["doc"] = "Module is loaded",
        ["long"] = "(L)",
        ["short"] = "(L)",
      },
    },
    validT = {
      ["active"] = 1,
    },
  },
}
```

**Comment by zao** [comment]
There shouldn't be any residual Debian configuration around as I've done a `apt purge lmod`.
The Lmod installation for 6.6.3 is a `configure/make/make install` without any arguments.

**Comment by zao** [comment]
After installing with the version 7 lmod, the installed module `Java/1.8` can be loaded using Lmod 6.6.3, so it seems to be only affecting the sanity check?

**Comment by boegel** [comment]
I just tried myself with a default Lmod 6.6.3 installation on macOS, and it worked just fine... Consider me confused.

@zao You mentioned that the `Java/1.8` alias is working fine with Lmod 6.6.3 after you've used Lmod 7.8.6 to make EasyBuild complete the installation procedure...

What does `LMOD_IGNORE_CACHE=1 $LMOD_CMD python load Java/1.8` using Lmod 6.6.3 produce for you?

Also, can you share you EasyBuild configuration (output of `eb --show-config` is enough)?

**Comment by zao** [comment]
```
os.environ["LMOD_DEFAULT_MODULEPATH"] = "/home/zao/.local/easybuild/modules/all:NONE/modulefiles/Linux:NONE/modulefiles/Core:/usr/local/lmod/lmod/modulefiles/Core";
os.environ["MODULEPATH"] = "/home/zao/.local/easybuild/modules/all:NONE/modulefiles/Linux:NONE/modulefiles/Core:/usr/local/lmod/lmod/modulefiles/Core";
os.environ["CPATH"] = "/home/zao/.local/easybuild/software/Java/1.8.0_181/include";
os.environ["EBDEVELJAVA"] = "/home/zao/.local/easybuild/software/Java/1.8.0_181/easybuild/Java-1.8.0_181-easybuild-devel";
os.environ["EBROOTJAVA"] = "/home/zao/.local/easybuild/software/Java/1.8.0_181";
os.environ["EBVERSIONJAVA"] = "1.8.0_181";
os.environ["JAVA_HOME"] = "/home/zao/.local/easybuild/software/Java/1.8.0_181";
os.environ["LD_LIBRARY_PATH"] = "/home/zao/.local/easybuild/software/Java/1.8.0_181/lib";
os.environ["LIBRARY_PATH"] = "/home/zao/.local/easybuild/software/Java/1.8.0_181/lib";
os.environ["LMOD_DEFAULT_MODULEPATH"] = "/home/zao/.local/easybuild/modules/all:NONE/modulefiles/Linux:NONE/modulefiles/Core:/usr/local/lmod/lmod/modulefiles/Core";
os.environ["LOADEDMODULES"] = "Java/1.8.0_181";
os.environ["MANPATH"] = "/home/zao/.local/easybuild/software/Java/1.8.0_181/man:/usr/local/lmod/lmod/share/man::";
os.environ["MODULEPATH"] = "/home/zao/.local/easybuild/modules/all:NONE/modulefiles/Linux:NONE/modulefiles/Core:/usr/local/lmod/lmod/modulefiles/Core";
os.environ["PATH"] = "/home/zao/.local/easybuild/software/Java/1.8.0_181:/home/zao/.local/easybuild/software/Java/1.8.0_181/bin:/home/zao/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/VulkanSDK/1.1.77.0/Bin:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files/CMake/bin:/mnt/c/Program Files/PuTTY:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/LLVM/bin:/mnt/c/Program Files/010 Editor:/mnt/c/Program Files (x86)/kaitai-struct-compiler/bin:/mnt/c/Program Files (x86)/GitExtensions:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/Lars/.cargo/bin:/mnt/c/Apps/Ruby24-x64/bin:/mnt/c/Users/Lars/AppData/Local/Microsoft/WindowsApps:/mnt/c/Utilities:/mnt/c/Apps/ffmpeg/bin:/mnt/c/Users/Lars/AppData/Local/Programs/Microsoft VS Code/bin";
os.environ["_LMFILES_"] = "/home/zao/.local/easybuild/modules/all/Java/1.8.0_181.lua";
os.environ["_ModuleTable001_"] = "X01vZHVsZVRhYmxlXz17WyJhY3RpdmVTaXplIl09MSxiYXNlTXBhdGhBPXsiL2hvbWUvemFvLy5sb2NhbC9lYXN5YnVpbGQvbW9kdWxlcy9hbGwiLCJOT05FL21vZHVsZWZpbGVzL0xpbnV4IiwiTk9ORS9tb2R1bGVmaWxlcy9Db3JlIiwiL3Vzci9sb2NhbC9sbW9kL2xtb2QvbW9kdWxlZmlsZXMvQ29yZSIsfSxbImNfcmVidWlsZFRpbWUiXT1mYWxzZSxbImNfc2hvcnRUaW1lIl09ZmFsc2UsZmFtaWx5PXt9LGluYWN0aXZlPXt9LG1UPXtKYXZhPXtbIkZOIl09Ii9ob21lL3phby8ubG9jYWwvZWFzeWJ1aWxkL21vZHVsZXMvYWxsL0phdmEvMS44LjBfMTgxLmx1YSIsWyJkZWZhdWx0Il09MCxbImZ1bGxOYW1lIl09IkphdmEvMS44LjBfMTgxIixbImxvYWRPcmRlciJdPTEscHJv";
os.environ["_ModuleTable002_"] = "cFQ9e30sWyJzaG9ydCJdPSJKYXZhIixbInN0YXR1cyJdPSJhY3RpdmUiLH0sfSxtcGF0aEE9eyIvaG9tZS96YW8vLmxvY2FsL2Vhc3lidWlsZC9tb2R1bGVzL2FsbCIsIk5PTkUvbW9kdWxlZmlsZXMvTGludXgiLCJOT05FL21vZHVsZWZpbGVzL0NvcmUiLCIvdXNyL2xvY2FsL2xtb2QvbG1vZC9tb2R1bGVmaWxlcy9Db3JlIix9LFsic3lzdGVtQmFzZU1QQVRIIl09Ik5PTkUvbW9kdWxlZmlsZXMvTGludXg6Tk9ORS9tb2R1bGVmaWxlcy9Db3JlOi91c3IvbG9jYWwvbG1vZC9sbW9kL21vZHVsZWZpbGVzL0NvcmUiLFsidmVyc2lvbiJdPTIsfQ==";
os.environ["_ModuleTable_Sz_"] = "2";
```
```
#
# Current EasyBuild configuration
# (C: command line argument, D: default value, E: environment variable, F: configuration file)
#
buildpath      (D) = /home/zao/.local/easybuild/build
containerpath  (D) = /home/zao/.local/easybuild/containers
installpath    (D) = /home/zao/.local/easybuild
repositorypath (D) = /home/zao/.local/easybuild/ebfiles_repo
robot-paths    (F) = /home/zao/Public/easybuild/easyconfigs, /home/zao/.local/easybuild/software/EasyBuild/3.7.0/lib/python2.7/site-packages/easybuild_easyconfigs-3.7.0-py2.7.egg/easybuild/easyconfigs
sourcepath     (D) = /home/zao/.local/easybuild/sources
```

**Comment by boegel** [comment]
@zao Can you please share a full debug log of an attempt to install the `Java/1.8` wrapper using Lmod 6.6.3?
Since you're not using a hierarchical MNS, this is a different problem than https://github.com/easybuilders/easybuild-easyblocks/issues/1534...

**Comment by zao** [comment]
I had to manually remove `/home/zao/.local/easybuild/modules/all/Java/.modulerc` for the rebuild to fail sanity checking, as the removal/recreation of an existing `.modulerc` is performed after the sanity check.

https://gist.github.com/zao/321f317e3f6bbef25e9bf094b624e10d#file-easybuild-java-1-8-20180929-232724-uuhdd-log

**Comment by boegel** [comment]
Can't seem to spot the cause of the problem in the debug log... My best guess is that a missing newline at the end is tripping things up, but that's a bit of a stretch.

@zao Can you please try again after applying the following patch to the `modulerc.py` easyblock? At the very least that'll give us a tiny bit more debug info.

```diff
diff --git a/easybuild/easyblocks/generic/modulerc.py b/easybuild/easyblocks/generic/modulerc.py
index c66760de7..1d8fff65e 100644
--- a/easybuild/easyblocks/generic/modulerc.py
+++ b/easybuild/easyblocks/generic/modulerc.py
@@ -79,7 +79,9 @@ class ModuleRC(EasyBlock):
 
         module_version_specs = {'modname': alias_modname, 'sym_version': self.version, 'version': deps[0]['version']}
         modulerc_txt = self.module_generator.modulerc(module_version=module_version_specs)
-        write_file(modulerc, modulerc_txt, backup=True)
+        write_file(modulerc, modulerc_txt + '\n', backup=True)
+
+        self.log.debug("Contents of %s:\n%s", modulerc, read_file(modulerc))
 
         if not fake:
             print_msg("created .modulerc file at %s" % modulerc, log=self.log)
```

Just for kicks, please also include the fix from https://github.com/easybuilders/easybuild-easyblocks/pull/1535/files, but that won't make any difference.

**Comment by zao** [comment]
Debug output for modulerc file, same failure at the end.
```
== 2018-09-30 00:27:59,755 modulerc.py:84 DEBUG Contents of /tmp/eb-__QxZ2/tmpL4WcNn/all/Java/.modulerc:
#%Module
module-version Java/1.8.0_181 1.8

== 2018-09-30 00:27:59,755 config.py:490 DEBUG modules install path as specified by 'installpath' and 'subdir_modules': /home/zao/.local/easybuild/modules
```

**Comment by zao** [comment]
Adding the temporary tree to the module path and running Lmod with debug flags shows that it seems to recognize the generated .modulerc in the /tmp tree, but not quite carry it through all the way:
https://gist.githubusercontent.com/zao/321f317e3f6bbef25e9bf094b624e10d/raw/9fe174108d3be80ccd8fcb46572e53eb81ec31e1/ml-debug-output.log

**Comment by boegel** [comment]
@zao On my system (macOS) with Lmod 6.6.3, I'm seeing the bloew in the debug output, which you are not seeing. This is where the translation from `Java/1.8` to `Java/1.8.0_181` is happening:

```
buildAvailT(mpath: /Users/kehoste/modules/all, path: /Users/kehoste/modules/all/Java,"Java", availT){
          walk_directory_for_mf(mpath: /Users/kehoste/modules/all, path: /Users/kehoste/modules/all/Java, prefix: "Java", dirA, mnameT){

            mnameT[Java/1.8.0_181].fn: /Users/kehoste/modules/all/Java/1.8.0_181.lua sn: Java, version: 1.8.0_181
          } walk_directory_for_mf
          defaultFn: /Users/kehoste/modules/all/Java/.modulerc, path: /Users/kehoste/modules/all/Java
          availT[Java].total: 1
          versionFile(v: /.modulerc, sn: Java, path: /Users/kehoste/modules/all/Java/.modulerc){
            handle file: /.modulerc
            capture(/usr/bin/tclsh /Users/kehoste/work/WIP/Lmod/lmod/lmod/libexec/RC2lua.tcl  /Users/kehoste/modules/all/Java/.modulerc){
              envT[LD_LIBRARY_PATH]=''
              newT[LD_LIBRARY_PATH]=''
              envT[LD_PRELOAD]=''
              newT[LD_PRELOAD]=''
unset LMOD_DEFAULT_MODULEPATH;
MODULEPATH="/Users/kehoste/modules/all:/usr/local/Cellar/lmod/7.8/modulefiles/Darwin:/usr/local/Cellar/lmod/7.8/modulefiles/Core";
export MODULEPATH;
              status: true, type(status): boolean
            } capture
            MAlias:parseModA(Java, modA){
              entry.kind: module-version
              resolve(modname): Java/1.8.0_181
              (2) modname: Java/1.8.0_181
              j: 1, version: 1.8
              v2m: key: Java/1.8: Java/1.8.0_181
            } MAlias:parseModA
            version: Java
          } versionFile
          return from versionFile: v: Java, f:/Users/kehoste/modules/all/Java/Java
        } buildAvailT
```

Then afterwards, it proceeds with actually loading `Java/1.8.0_181`, see full debug log in https://gist.github.com/boegel/cf21341ffe671e8cdb3f8270732e7fa5 .

I'm starting to think this is some kind of file sync issue in WSL... I.e. Lmod isn't actually seeing the contents of the `.modulerc` yet shortly after it is written?

**Comment by zao** [comment]
I'm not certain that sync problems would be the whole story, as my separate Lmod load as linked above was done long after the write of the file, even after manual inspection in a text editor.

Note that there's a possibly significant difference between our runs, in that in your debug output, you have both the `.modulerc` and the module in the same path, while in mine the `.modulerc` is down in `/tmp` and the u181 Java is in the installed EB target tree.

Of course, I can't yet explain the difference in sanity check behaviour. Make sure that you have removed the old `.modulerc` in the EB tree before rebuilding Java/1.8, even with `--force` a lingering file will still trick the sanity check into passing.

**Comment by zao** [comment]
I've installed a fresh Ubuntu 16.04 physical machine, installed Lmod 6.6.3 from source package, bootstrapped EasyBuild 3.7.0.

It fails out of the box installing Java/1.8.

```bash
export EASYBUILD_PREFIX=$HOME/.local/easybuild
source /opt/Lmod-6.6.3/lmod/lmod/init/profile
~/bootstrap_eb.py $EASYBUILD_PREFIX
module use $EASYBUILD_PREFIX/modules/all
ml EasyBuild
eb Java-1.8.eb --robot
```

**Comment by boegel** [comment]
@zao The module load during the sanity check is always done for a module in a temporary location, so also in my case the `Java/1.8.0_181` is in another location (`$HOME/modules/all/Java` in my case).

I also manually remove the `.modulerc` file to try and trigger the failure, but I'm unable to reproduce the issue.

Your last attempt is outside of WSL? Can you provide a full debug log for that failing attempt? If possible with the extra debug info from before (see patch suggested above).

**Comment by zao** [comment]
It was entirely outside of WSL, on a machine running Ubuntu 16.04 on bare metal.
Log from EB with the patch applied:
https://gist.githubusercontent.com/zao/38267372f2f09abfed6483148c5b42dd/raw/a2511c72959ca8813178050ea1b40c85a92e47af/easybuild-Java-1.8-20180930.175203.malEL.log

**Comment by zao** [comment]
I've dug a bit, copied the relevant modules into a separate set of directories to `ml use`. It only succeeds if they coexist in the exact same module tree.
```
zao@hodor:~/modproblem$ find -type f -ls
  2359660      4 -rw-rw-r--   1 zao      zao          1027 Sep 30 17:59 ./justlong/all/Java/1.8.0_181.lua
  2359661      4 -rw-rw-r--   1 zao      zao          1027 Sep 30 17:59 ./both/all/Java/1.8.0_181.lua
  2359663      4 -rw-rw-r--   1 zao      zao            43 Sep 30 17:59 ./both/all/Java/.modulerc
  2359662      4 -rw-rw-r--   1 zao      zao            43 Sep 30 17:59 ./justshort/all/Java/.modulerc
zao@hodor:~/modproblem$ (source /opt/Lmod-6.6.3/lmod/lmod/init/profile; ml use ~/modproblem/justshort/all ~/modproblem/justlong/all; ml Java/1.8)
Lmod has detected the following error:  The following module(s) are unknown: "Java/1.8"

Please check the spelling or version number. Also try "module spider ..."



zao@hodor:~/modproblem$ (source /opt/Lmod-6.6.3/lmod/lmod/init/profile; ml use ~/modproblem/justlong/all ~/modproblem/justshort/all; ml Java/1.8)
Lmod has detected the following error:  The following module(s) are unknown: "Java/1.8"

Please check the spelling or version number. Also try "module spider ..."



zao@hodor:~/modproblem$ (source /opt/Lmod-6.6.3/lmod/lmod/init/profile; ml use ~/modproblem/both/all; ml Java/1.8)
zao@hodor:~/modproblem$
```

**Comment by boegel** [comment]
@zao Ah, that kind of explains it. I'm seeing the same issue:

```
find /tmp/issue462 -type f
/tmp/issue462/justlong/all/Java/1.8.0_181.lua
/tmp/issue462/justshort/all/Java/.modulerc

$ (echo $MODULEPATH; ml use /tmp/issue462/justlong/all/  /tmp/issue462/justshort/all/; ml av Java; ml Java/1.8; ml)

----------- /tmp/issue462/justlong/all -----------
   Java/1.8.0_181 (1.8)

Use "module spider" to find all possible modules.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".

Lmod has detected the following error:  The following module(s) are unknown: "Java/1.8"

Please check the spelling or version number. Also try "module spider ..."

No modules loaded
```

Note the `(1.8)` in the `ml av Java` output. So Lmod *is* seeing the symbolic version, but it trips over the actual module being in another location... I guess this is a problem fixed in Lmod 7.x.

I've also figured out why I failed to reproduce your problem on my end: whenever I was running `eb`, it wasn't picking up the Lmod installation I wanted to, it kept picking up my system-wide Lmod 7.8 installation... >_<

Now that we've figured it out, I guess the question becomes how to solve this...

Do we copy the module being wrapped into the temporary location when creating the `.modulerc`?

What if the `Java` module file was installed in location A, and the (final) installation prefix for the `.modulerc` is location B? Then it can basically never work with Lmod 6.x, and we should warn about that (or worse, error out)?

**Comment by zao** [comment]
I completely understand the problems with reproducing it, Lmod is very symlink-happy and quite often manages to pick up the wrong thing if installed into similar prefixes - I ended up having to have completely disjoint installation trees with no global one, and activating them on demand in subshells.

If copying, could there technically be any problems if the wrapped module has some interesting contents that rely on the proper location, or is this process not touching enough of the module innards to matter?

SoftInst comes to mind when talking about multiple locations. In this case it's highly unlikely that an administrator installs a long version and an end user installs a short version, but if ModuleRC is to be a generic thing, it might be a problem.

**Comment by zao** [comment]
Looking at the kind of modules impacted by this, the big one I ran into this with is R-3.5.1-foss-2018b, so it's not exactly a small consumer.

Would it make sense to keep a minimum Lmod version of the 6 series if it can't handle some of the modules in the distribution, or should the minimum be painstakingly bumped to a 7.x series?

**Comment by vanzod** [comment]
@zao The fix has been merged. Please test it again and let us know if this issue can be closed.

**Comment by boegel** [comment]
@vanzod No, the fix in https://github.com/easybuilders/easybuild-framework/pull/2597 only fixes your problem of required `tclsh` with Lmod 7.8 even though it supports `.modulerc` in Lua syntax...

The problem reported by @zao here is a different issue, where Lmod 6.x behaves differently than Lmod 7.x. With Lmod 6.x, both the `.modulerc` and the module file being wrapped must be in the same directory...

**Comment by boegel** [comment]
@zao This problem should be fixed with the changes in https://github.com/easybuilders/easybuild-easyblocks/pull/1539 (which requires https://github.com/easybuilders/easybuild-framework/pull/2611)

cc @verdurin

**Comment by boegel** [comment]
fixed with https://github.com/easybuilders/easybuild-easyblocks/pull/1539 (included in EasyBuild v3.7.1)
